I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/branch3.rpy", line 171, in script
    show jeffrey_normal at entetrr1
  File "game/branch3.rpy", line 171, in <module>
    show jeffrey_normal at entetrr1
NameError: name 'entetrr1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/branch3.rpy", line 171, in script
    show jeffrey_normal at entetrr1
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/ast.py", line 1156, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/branch3.rpy", line 171, in <module>
    show jeffrey_normal at entetrr1
NameError: name 'entetrr1' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
jcafe_vn_projek_besar 1.0
Sat Jan  7 20:54:54 2023
